### ISSUE TITLE
Add support for ternary expression values

### ISSUE THREAD

**Issue by iansan5653** [iansan5653/primer-sx-to-css-converter#5]
For simple ternary expressions, we could split into two class definitions using a nesting selector. So this:

```ts
const sx = {
  color: variant === 'danger' ? 'danger.fg' : 'fg.default'
}
```

Could become:

```css
.className {
  color: var(--fgColor-default);

  &.variant1ClassName {
    color: var(--fgColor-danger);
  }
}
```

### Multiple ternaries

If we have multiple ternaries relying on the same logic, we should combine them:

```ts
const sx = {
  color: variant === 'danger' ? 'fg.onEmphasis' : 'fg.default',
  bg: variant === 'danger' ? 'danger.emphasis' : 'canvas.default'
}
```

Should become:

```css
.className {
  color: var(--fgColor-default);
  background: var(--bgColor-default);

  &.variant1ClassName {
    color: var(--fgColor-onEmphasis);
    background: var(--bgColor-danger-emphasis);
  }
}
```

### Class naming

We _could_ try to generate class names automatically for very simple cases:

- `a === b`: `.aIsB`
- `a > 45`: `.aIsMoreThan45`
- `!!a`: `aIsTruthy`
- `!a`: `aIsFalsy`

So for basic comparisons we can get a decent result: `variantIsDanger`, `widthIsMoreThan5`, `childrenIsTruthy`, etc.
